### ISSUE TITLE
Environment variables in release notes settings are replaced by concrete values

### ISSUE THREAD

**Issue by pathob** [DavidHamm/google-play-publisher#35]
Hey David,

thanks to your nice work, I prefere this plugin instead of the other publisher plugin by orrc. But unfortunately environment variables like ${BUILD_NUMBER} in the release notes settings are replaced by conrete values of the first build happening after changing the release notes and stay at this value.

Hope this could be fixed, thanks.

hob

**Comment by DavidHamm** [comment]
hi pathob,

i found the issue in the code and i will try to fix it.

regards
david
